name: Rust

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

env:
  CARGO_TERM_COLOR: always

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v3
    - name: Update local toolchain
      run: |
        rustup update
        rustup component add clippy rustfmt
    - name: Format
      run: cargo fmt --all -- --check
    - name: Clippy
      run: cargo clippy -- -Dwarnings
    - name: Build
      run: cargo build --verbose
